version: '3.1'

services:

  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=upwork
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - $HOME/docker/volumes/upwork-cs:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
      timeout: 3s
      retries: 10
    ports:
      - 5432:5432

  golang:
    # image: golang:alpine
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_NAME=upwork
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_HOST=postgres
      - DB_PORT=5432
    ports:
      - 8080:8080
    volumes:
      - ./:/upwork-cs
    working_dir: /upwork-cs
    command: go run main.go
