
# syntax=docker/dockerfile:1

FROM golang:alpine AS build

WORKDIR /app 

COPY go.mod .
COPY go.sum .

RUN go mod download


COPY ./internal ./internal
COPY ./model ./model
COPY ./pkg ./pkg

COPY *.go ./

RUN go build -o /upwork

FROM gcr.io/distroless/base-debian10

WORKDIR /

COPY --from=build /upwork /upwork

EXPOSE 8080

USER nonroot:nonroot

ENTRYPOINT ["/upwork"]